apiVersion: apps/v1
kind: Deployment
metadata:
  name: robo-deployemnt
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: robo
  template:
    metadata:
      labels:
        app: robo
    spec:
      containers:
      - name: robo
        image: 982641132963.dkr.ecr.eu-west-1.amazonaws.com/robo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: robo-service
spec:
  selector:
    app: robo
  ports:
    - name: https
      protocol: TCP
      port: 8080
      targetPort: 3000
  type: LoadBalancer
  